// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDac6QjpjkZdXXwyxextpq1SDvqeID7RiE',
    appId: '1:911535585380:web:2a4e8bd9ca2c7e463d8771',
    messagingSenderId: '911535585380',
    projectId: 'sensordatairrigation',
    authDomain: 'sensordatairrigation.firebaseapp.com',
    databaseURL: 'https://sensordatairrigation-default-rtdb.firebaseio.com',
    storageBucket: 'sensordatairrigation.firebasestorage.app',
    measurementId: 'G-LJGPD1P3M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5QRYRw51kd_eyjT_70dfvc5uwG33hGs',
    appId: '1:911535585380:android:3621111b7cbab3423d8771',
    messagingSenderId: '911535585380',
    projectId: 'sensordatairrigation',
    databaseURL: 'https://sensordatairrigation-default-rtdb.firebaseio.com',
    storageBucket: 'sensordatairrigation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ehkOQsn8jciwZzAZdg8tUBhE46F9dqc',
    appId: '1:911535585380:ios:1c069a0d3376970b3d8771',
    messagingSenderId: '911535585380',
    projectId: 'sensordatairrigation',
    databaseURL: 'https://sensordatairrigation-default-rtdb.firebaseio.com',
    storageBucket: 'sensordatairrigation.firebasestorage.app',
    iosBundleId: 'com.example.irrigationMonitor',
  );
}
